[package]
name = "re-sound"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5"
strum = { version = "0.27", features = ["derive"] }
thiserror = "2.0"

serde = { version = "1", features = ["derive"], optional = true }
binrw = "0.14.1"

[features]
default = ["serde"]
