[package]
name = "re-sound"
version = "0.3.2"
edition = "2024"

[dependencies]
byteorder = "1.5"
strum = { version = "0.27", features = ["derive"] }
thiserror = "2.0"
binrw = "0.15"
serde = { version = "1", features = ["derive"], optional = true }

[features]
default = ["serde"]
